### ISSUE TITLE
Failed to parse workflow: error unmarshaling JSON: while decoding JSON: json: unknown field "gcs"

### ISSUE THREAD

**Issue by geewynn** [machine-learning-apps/gke-argo#3]
Please @hamelsmu  Is there a way we can upgrade the argo version of this action?

I am trying to run the action and it fails when parsing GCS file as shown in the image below.
![Screenshot from 2021-01-21 11-19-23](https://user-images.githubusercontent.com/29405050/105337667-ed781480-5bda-11eb-917b-990bcae3fcc7.png)

I am able to run my argo workflow file without that error but each time I use it on GitHub action, it fails.

This is a section of my GitHub action workflow.yaml
```
- name: Submit Argo Deployment
      #if: steps.label.outputs.TRIGGERED == 'true'
      id: argo
      uses: machine-learning-apps/gke-argo@master
      with:
        ARGO_URL: ${{ secrets.ARGO_URI }}
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
        LOCATION_ZONE: "us-east4-a"
        CLUSTER_NAME: "kubearg"
        WORKFLOW_YAML_PATH: "pipelines/workflow.yaml" # the argo workflow file relative to the repo's root.
        SHA: ${{ steps.label.outputs.HEAD_SHA }}
```

and this is the part of my argo workflow.yaml file
```
outputs:
     artifacts:
     - name: dataset
       path: /data
       gcs:
        bucket: bucket-name
        key: dataset
        serviceAccountKeySecret:
          name: my-gcs-credentials
          key: serviceAccountKey
```

This is the version of my standalone argo setup
```
argo: v2.12.5
  BuildDate: 2021-01-19T22:35:05Z
  GitCommit: 53f022c3f740b5a8636d74873462011702403e42
  GitTreeState: clean
  GitTag: v2.12.5
  GoVersion: go1.13
  Compiler: gc
  Platform: linux/amd64
```

Thank you
